# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            My Portfolio
tagline:          ''
description:      'My online portfolio, Made by Layne Brown.'
url:              http://Layne-brown.github.io
baseurl:          /

author:
  name:           'Layne Brown'
  url:           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
